import React from 'react'
import Image from 'next/image'
const page = () => {
  return (
    <div className="min-h-screen bg-gray-100 p-4"> <div className="flex flex-col lg:flex-row"> {/* Main Menu */} <div className="w-full lg:w-1/5 bg-white p-4 rounded-lg shadow-md mb-4 lg:mb-0"> <ul className="space-y-4"> <li className="font-bold text-blue-600">Dashboard</li> <li>Car Rent</li> <li>Insight</li> <li>Reimburse</li> <li>Inbox</li> <li>Calendar</li> <li>Settings</li> <li>Help & Center</li> <li>Dark Mode</li> <li>Log Out</li> </ul> </div> {/* Main Content */} <div className="w-full lg:w-4/5 lg:pl-4"> <div className="grid grid-cols-1 lg:grid-cols-3 gap-4"> {/* Details Rental */} <div className="col-span-2 bg-white p-4 rounded-lg shadow-md"> <div className="mb-4"> <Image src="/map.png" alt="Map" width={500} height={200} className="w-full h-40 object-cover rounded-lg" /> 
    </div> 
    <div className="flex items-center mb-4"> 
    <Image src="/Img/Detail_Car1.svg" alt="Nissan GT-R" width={64} height={64} className="w-16 h-16 rounded-lg mr-4" /> <div> <h2 className="text-xl font-bold">Nissan GT-R</h2> <p className="text-gray-500">Sport Car</p> </div> </div> <div className="grid grid-cols-2 gap-4"> <div> <h3 className="font-bold">Pick-Up</h3> <p>Location: Kota Semarang</p> <p>Date: 20 July 2022</p> <p>Time: 07:00</p> </div> <div> <h3 className="font-bold">Drop-Off</h3> <p>Location: Kota Semarang</p> <p>Date: 21 July 2022</p> <p>Time: 01:00</p> </div> </div> <div className="mt-4"> <h3 className="text-xl font-bold">Total Rental Price</h3> <p className="text-2xl font-bold text-blue-600">$80.00</p> </div> </div> {/* Top 5 Car Rental */} <div className="bg-white p-4 rounded-lg shadow-md"> <h3 className="text-xl font-bold mb-4">Top 5 Car Rental</h3> <div className="flex items-center justify-center mb-4"> <div className="relative w-32 h-32"> <svg className="absolute inset-0 w-full h-full"> <circle cx="50%" cy="50%" r="50%" fill="none" stroke="#e5e7eb" strokeWidth="8" /> <circle cx="50%" cy="50%" r="50%" fill="none" stroke="#3b82f6" strokeWidth="8" strokeDasharray="calc(72 / 100 * 314.16) 314.16" /> </svg> <div className="absolute inset-0 flex items-center justify-center"> <span className="text-2xl font-bold">72%</span> </div> </div> </div> <ul className="space-y-2 text-gray-700"> <li>Sport Car: 150</li> <li>SUV: 100</li> <li>Coupe: 80</li> <li>Hatchback: 70</li> <li>MPV: 50</li> </ul> </div> {/* Recent Transaction */} <div className="col-span-3 bg-white p-4 rounded-lg shadow-md mt-4 lg:mt-0"> <h3 className="text-xl font-bold mb-4">Recent Transactions</h3> <table className="w-full"> <thead> <tr> <th className="text-left">Car Model</th> <th className="text-left">Type</th> <th className="text-left">Date</th> <th className="text-left">Price</th> </tr> </thead> <tbody> <tr> <td>Nissan GT-R</td> <td>Sport Car</td> <td>20 July 2022</td> <td>$80.00</td> </tr> <tr> <td>Honda Civic</td> <td>SUV</td> <td>18 July 2022</td> <td>$60.00</td> </tr> <tr> <td>Toyota Corolla</td> <td>Coupe</td> <td>15 July 2022</td> <td>$50.00</td> </tr> </tbody> </table> </div> </div> </div> </div> </div>
  )
}

export default page